import marimo

__generated_with = "0.22.4"
app = marimo.App(width="medium")


@app.cell
def _():
    from galaga import Algebra
    from galaga.blade_convention import b_default
    import galaga_marimo as gm
    import marimo as mo
    import numpy as np
    import matplotlib.pyplot as plt

    return Algebra, b_default, gm, mo, np, plt


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Pin and Spin from Reflections

    Rotors are even versors, but the larger story is that reflections generate
    the whole Pin group. Even products of reflection normals lie in Spin; odd
    products stay in Pin but reverse orientation.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    We use $\mathrm{Cl}(2,0)$ and build versors from mirror normals

    $$
    V = n_k n_{k-1} \cdots n_1.
    $$

    Then the sandwich action

    $$
    x' = \pm V x \widetilde V
    $$

    gives the geometric transformation. The parity of the number of reflections is
    the important structural fact:

    - odd number of reflections: orientation-reversing, Pin but not Spin
    - even number of reflections: orientation-preserving rotor, in Spin
    """)
    return


@app.cell
def _(Algebra, b_default):
    alg = Algebra((1, 1), blades=b_default())
    e1, e2 = alg.basis_vectors(lazy=True)
    return alg, e1, e2


@app.cell
def _(mo):
    count = mo.ui.dropdown(options=["1 reflection", "2 reflections", "3 reflections"], value="2 reflections", label="Number of reflections")
    alpha = mo.ui.slider(0, 360, step=1, value=15, label="Mirror 1 line angle", show_value=True)
    beta = mo.ui.slider(0, 360, step=1, value=70, label="Mirror 2 line angle", show_value=True)
    gamma = mo.ui.slider(0, 360, step=1, value=135, label="Mirror 3 line angle", show_value=True)
    vector_angle = mo.ui.slider(0, 180, step=1, value=20, label="Input vector angle", show_value=True)
    return alpha, beta, count, gamma, vector_angle


@app.cell
def _(alpha, beta, count, draw_pin_spin, e1, e2, gamma, gm, mo, np, vector_angle):
    def _normal_from_line_angle(_deg, _label):
        _a = np.radians(_deg)
        _line = np.cos(_a) * e1 + np.sin(_a) * e2
        return ((-_line | e2) * e1 + (_line | e1) * e2).eval().name(latex=_label)

    n1 = _normal_from_line_angle(alpha.value, r"n_1")
    n2 = _normal_from_line_angle(beta.value, r"n_2")
    n3 = _normal_from_line_angle(gamma.value, r"n_3")
    x = (np.cos(np.radians(vector_angle.value)) * e1 + np.sin(np.radians(vector_angle.value)) * e2).name(latex="x")

    _num = int(count.value[0])
    _normals = [n1, n2, n3][: _num]
    V = _normals[-1]
    for _n in reversed(_normals[:-1]):
        V = V * _n
    V = V.name(latex="V")

    x_curr = x
    _steps = []
    for _n in _normals:
        x_curr = (-_n * x_curr * _n).name(latex=rf"x_{{{len(_steps)+1}}}")
        _steps.append(x_curr)
    x_final = _steps[-1].name(latex=r"x'")

    _parity = "even" if _num % 2 == 0 else "odd"
    _membership = r"\mathrm{Spin}(2)" if _num % 2 == 0 else r"\mathrm{Pin}(2)\setminus \mathrm{Spin}(2)"
    _orientation = "orientation-preserving rotation" if _num % 2 == 0 else "orientation-reversing reflection-like action"

    _step_md = " <br/>\n".join(_step.display() for _step in _steps)
    _md = t"""
    {n1.display()} <br/>
    {n2.display()} <br/>
    {n3.display()} <br/>
    {x.display()} <br/>
    {V.display()} <br/>
    {_step_md} <br/>
    Number of reflections: ${_num}$ ({_parity} parity) <br/>
    Group membership: ${_membership}$ <br/>
    Net action: {_orientation}
    """

    mo.vstack([count, alpha, beta, gamma, vector_angle, gm.md(_md), draw_pin_spin(_normals, x, _steps, _num)])
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Key Point

    Rotors are not the whole reflection story. They are the even part of it.
    Pin is generated by reflections in general, and Spin is the even subcollection
    where orientation reversal cancels out.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""## Appendum: Plotting Code""")
    return


@app.cell(hide_code=True)
def _(plt):
    def draw_pin_spin(normals, x, steps, count):
        _fig, _ax = plt.subplots(figsize=(6.2, 6.2))

        _colors = ["#2563eb", "#f59e0b", "#10b981"]
        for _n, _color in zip(normals, _colors):
            _a = _n.vector_part[:2]
            _m = np.array([-_a[1], _a[0]])
            _ax.plot([-2.6 * _m[0], 2.6 * _m[0]], [-2.6 * _m[1], 2.6 * _m[1]], color=_color, alpha=0.35, linewidth=2.0)
            _ax.annotate("", xy=_a, xytext=(0, 0), arrowprops=dict(arrowstyle="-|>", color=_color, lw=1.3, alpha=0.35, linestyle="--"))

        _vectors = [x] + steps
        _vec_colors = ["#222222", "#444444", "#7c3aed", "#d62828"]
        _labels = ["x", "after 1", "after 2", "after 3"]
        for _v, _color, _label in zip(_vectors, _vec_colors, _labels):
            _xy = _v.vector_part[:2]
            _alpha = 0.35 if "after" in _label and _label != f"after {count}" else 1.0
            _lw = 2.6 if _label == f"after {count}" or _label == "x" else 2.0
            _ax.annotate("", xy=_xy, xytext=(0, 0), arrowprops=dict(arrowstyle="-|>", color=_color, lw=_lw, alpha=_alpha))
            if _label == "x" or _label == f"after {count}":
                _ax.text(_xy[0] + 0.06, _xy[1] + 0.05, _label, color=_color)

        _ax.set_xlim(-2.1, 2.1)
        _ax.set_ylim(-2.1, 2.1)
        _ax.set_aspect("equal")
        _ax.grid(True, alpha=0.18)
        _ax.set_xlabel("e1")
        _ax.set_ylabel("e2")
        _ax.set_title("Reflections generate Pin; even parity lands in Spin")
        plt.close(_fig)
        return _fig

    return (draw_pin_spin,)


@app.cell
def _():
    return


if __name__ == "__main__":
    app.run()
