import marimo

__generated_with = "0.21.1"
app = marimo.App(width="medium")


@app.cell
def _():
    from galaga import Algebra, exp, log, sandwich, unit
    from galaga.notation import Notation
    import galaga_marimo as gm
    import numpy as np
    import marimo as mo
    import matplotlib.pyplot as plt

    return Algebra, Notation, exp, gm, log, mo, np, plt, sandwich, unit


@app.cell
def _(np, plt):
    def draw_slerp_3d(v, v0, v1, vt):
        fig = plt.figure(figsize=(7, 6))
        ax = fig.add_subplot(111, projection="3d")

        u = np.linspace(0, 2 * np.pi, 32)
        w = np.linspace(0, np.pi, 18)
        x = np.outer(np.cos(u), np.sin(w))
        y = np.outer(np.sin(u), np.sin(w))
        z = np.outer(np.ones_like(u), np.cos(w))
        ax.plot_wireframe(x, y, z, color="gray", alpha=0.08)

        def arrow(vec, color, label):
            vx, vy, vz = vec.vector_part[:3]
            ax.quiver(0, 0, 0, vx, vy, vz, color=color, linewidth=2.5, arrow_length_ratio=0.08, label=label)

        arrow(v, "black", "input vector")
        arrow(v0, "steelblue", "R0 v R̃0")
        arrow(v1, "darkorange", "R1 v R̃1")
        arrow(vt, "crimson", "R(t) v R̃(t)")

        ax.set_xlim(-1.1, 1.1)
        ax.set_ylim(-1.1, 1.1)
        ax.set_zlim(-1.1, 1.1)
        ax.set_box_aspect((1, 1, 1))
        ax.set_xlabel("e1")
        ax.set_ylabel("e2")
        ax.set_zlabel("e3")
        ax.set_title("3D action of slerped rotors")
        ax.legend(loc="upper left")
        plt.close(fig)
        return fig

    return (draw_slerp_3d,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # 3D Slerp with Rotors

    In 2D, rotor interpolation can feel like complex numbers in disguise. In 3D the gain is clearer: rotors can be generated by different bivector planes, and slerp still gives one clean interpolation rule.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    We start with the 3D Euclidean geometric algebra $\mathrm{Cl}(3,0)$.

    Its even subalgebra is spanned by one scalar and three bivectors: $1$, $e_{12}$, $e_{23}$, and $e_{13}$. That means full rotor space is four-dimensional, so instead of plotting the rotor itself, we visualize what the interpolated rotor does to a 3D vector.
    """)
    return


@app.cell
def _(Algebra, Notation):
    alg = Algebra((1, 1, 1), notation=Notation.default())
    e1, e2, e3 = alg.basis_vectors(lazy=True)
    return alg, e1, e2, e3


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Slerp Between Different Rotation Planes

    Given two rotors $R_0$ and $R_1$, we form the relative rotor

    $$
    \Delta = \widetilde{R_0} R_1
    $$

    and interpolate by

    $$
    R(t) = R_0 \exp\!\bigl(t \log(\Delta)\bigr).
    $$

    The same formula works even when $R_0$ and $R_1$ come from different bivector planes. That is where the geometric algebra viewpoint starts to earn its keep.
    """)
    return


@app.cell
def _(mo):
    plane_0 = mo.ui.dropdown(
        options={
            "e12 plane": "e12",
            "e23 plane": "e23",
            "e13 plane": "e13",
        },
        value="e12 plane",
        label="Start plane",
    )
    angle_0 = mo.ui.slider(0, 180, step=1, value=35, label="Start angle θ0", show_value=True)
    plane_1 = mo.ui.dropdown(
        options={
            "e12 plane": "e12",
            "e23 plane": "e23",
            "e13 plane": "e13",
        },
        value="e23 plane",
        label="End plane",
    )
    angle_1 = mo.ui.slider(0, 180, step=1, value=120, label="End angle θ1", show_value=True)
    blend = mo.ui.slider(0.0, 1.0, step=0.01, value=0.5, label="Blend t", show_value=True)
    return angle_0, angle_1, blend, plane_0, plane_1


@app.cell
def _(
    alg,
    angle_0,
    angle_1,
    blend,
    draw_slerp_3d,
    e1,
    e2,
    e3,
    exp,
    gm,
    log,
    mo,
    np,
    plane_0,
    plane_1,
    sandwich,
    unit,
):
    planes = {
        "e12": (e1 * e2).name("e_{12}"),
        "e23": (e2 * e3).name("e_{23}"),
        "e13": (e1 * e3).name("e_{13}"),
    }

    B0 = unit(planes[plane_0.value]).name("B_0")
    B1 = unit(planes[plane_1.value]).name("B_1")
    theta0 = alg.scalar(np.radians(angle_0.value)).name(latex=r"\theta_0")
    theta1 = alg.scalar(np.radians(angle_1.value)).name(latex=r"\theta_1")

    R0 = exp(-B0 * theta0 / 2).name("R_0")
    R1 = exp(-B1 * theta1 / 2).name("R_1")
    Delta = (~R0 * R1).name(r"\Delta")
    Rt = (R0 * exp(blend.value * log(Delta))).name("R(t)")

    v = unit(e1 + 0.6 * e2 + 0.2 * e3).name("v")
    v0 = sandwich(R0, v).name("v_0")
    v1 = sandwich(R1, v).name("v_1")
    vt = sandwich(Rt, v).name("v_t")

    _md = t"""
    {B0.display()} $\\quad$ and $\\quad$ {B1.display()} <br/>
    {R0.display()} <br/>
    {R1.display()} <br/>
    {Delta.display()} <br/>
    {log(Delta).display()} <br/>
    {Rt.display()} <br/>
    {(Rt * ~Rt).display()} <br/>
    {v.display()} <br/>
    {vt.display()} <br/>
    With $t = {blend.value:.2f}$, the interpolated rotor is a fractional step along the relative 3D rotation between $R_0$ and $R_1$, not a linear blend of coefficients.
    """

    mo.vstack([plane_0, angle_0, plane_1, angle_1, blend, gm.md(_md), draw_slerp_3d(v, v0, v1, vt)])
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Why This Example Is Better Than 2D

    In 2D, slerp is almost the same story as complex-number interpolation on the unit circle. In 3D, the bivector generator itself can change direction, and the same rotor formula still works without switching frameworks. That is the stronger geometric algebra story.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Conclusion

    The 3D case shows the real advantage of rotor slerp in geometric algebra: one interpolation rule handles rotations generated by different planes, keeps the result normalized, and acts directly on vectors through the same sandwich product as before.
    """)
    return


@app.cell
def _():
    return


if __name__ == "__main__":
    app.run()
