import marimo

__generated_with = "0.21.1"
app = marimo.App(width="medium")


@app.cell
def _():
    from galaga import Algebra, exp, sandwich
    import galaga_marimo as gm
    import numpy as np
    import marimo as mo
    import matplotlib.pyplot as plt

    return Algebra, exp, gm, mo, np, plt, sandwich


@app.cell
def _(np, plt):
    def draw_worldlines(beta, c, g, light_year_m, t_acc, t_coast, tau_acc, tau_coast, total_distance, total_earth_time, x_acc, year_s):
        import matplotlib.ticker as _mticker

        def _comma_fmt(x, _pos):
            if abs(x - round(x)) < 1e-9:
                return f"{x:,.0f}"
            return f"{x:,.3f}".rstrip("0").rstrip(".")

        _n = 240
        _phi = g * tau_acc / c
        _gamma = np.cosh(_phi)
        _x_coast = beta * c * t_coast

        _t1 = np.linspace(0.0, t_acc, _n)
        _x1 = np.sqrt((c**2 / g) ** 2 + (c * _t1) ** 2) - (c**2 / g)

        _t2 = np.linspace(t_acc, t_acc + t_coast, max(2, _n // 2))
        _x2 = x_acc + beta * c * (_t2 - t_acc)

        _tau1 = np.linspace(0.0, tau_acc, _n)
        _tau2 = np.linspace(tau_acc, tau_acc + tau_coast, max(2, _n // 2))
        _tau3 = np.linspace(tau_acc + tau_coast, 2.0 * tau_acc + tau_coast, _n)
        _tau3_local = np.linspace(0.0, tau_acc, _n)
        _x1_ship = (c**2 / g) * (np.cosh(g * _tau1 / c) - 1.0)
        _x2_ship = x_acc + beta * c * _gamma * (_tau2 - tau_acc)
        _x3_ship = total_distance - (c**2 / g) * (np.cosh(_phi - g * _tau3_local / c) - 1.0)
        _t3 = t_acc + t_coast + (c / g) * (np.sinh(_phi) - np.sinh(_phi - g * _tau3_local / c))
        _x3 = x_acc + _x_coast + (c**2 / g) * (np.cosh(_phi) - np.cosh(_phi - g * _tau3_local / c))

        _fig, (_ax_ship, _ax_earth) = plt.subplots(1, 2, figsize=(12, 5.2))

        _ax_ship.plot(_tau1 / year_s, _x1_ship / light_year_m, color="crimson", linewidth=2.5, label="accelerate")
        if tau_coast > 0:
            _ax_ship.plot(_tau2 / year_s, _x2_ship / light_year_m, color="steelblue", linewidth=2.5, label="coast")
        _ax_ship.plot(_tau3 / year_s, _x3_ship / light_year_m, color="darkorange", linewidth=2.5, label="decelerate")
        _ax_ship.set_xlabel("Ship time (years)")
        _ax_ship.set_ylabel("Distance from Earth (light-years)")
        _ax_ship.set_title("Worldline vs ship proper time")
        _ax_ship.grid(True, alpha=0.25)
        _ax_ship.legend(loc="upper left")
        _ax_ship.xaxis.set_major_formatter(_mticker.FuncFormatter(_comma_fmt))
        _ax_ship.yaxis.set_major_formatter(_mticker.FuncFormatter(_comma_fmt))

        _ax_earth.plot(_t1 / year_s, _x1 / light_year_m, color="crimson", linewidth=2.5, label="accelerate")
        if t_coast > 0:
            _ax_earth.plot(_t2 / year_s, _x2 / light_year_m, color="steelblue", linewidth=2.5, label="coast")
        _ax_earth.plot(_t3 / year_s, _x3 / light_year_m, color="darkorange", linewidth=2.5, label="decelerate")
        _ax_earth.set_xlabel("Earth time (years)")
        _ax_earth.set_ylabel("Distance from Earth (light-years)")
        _ax_earth.set_title("Worldline vs Earth time")
        _ax_earth.grid(True, alpha=0.25)
        _ax_earth.legend(loc="upper left")
        _ax_earth.xaxis.set_major_formatter(_mticker.FuncFormatter(_comma_fmt))
        _ax_earth.yaxis.set_major_formatter(_mticker.FuncFormatter(_comma_fmt))
        plt.close(_fig)
        return _fig

    return (draw_worldlines,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # 1g Relativistic Travel

    Constant proper acceleration is one of the cleanest places to see why rapidity is the natural relativistic variable. In the traveler's frame, proper acceleration builds rapidity linearly; in the Earth frame, time and distance grow hyperbolically.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    We build the spacetime algebra $\mathrm{Cl}(1,3)$ with signature $(+,-,-,-)$.

    For motion along one spatial direction, boosts are generated by the timelike bivector $\gamma_0\gamma_1$. Constant proper acceleration then gives the rapidity law

    $$
    \varphi = \frac{a\tau}{c},
    $$

    where $\tau$ is ship time.
    """)
    return


@app.cell
def _(Algebra):
    sta = Algebra((1, -1, -1, -1), names="gamma")
    g0, g1, g2, g3 = sta.basis_vectors(lazy=True)
    return g0, g1, sta


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Burn, Coast, Burn

    The journey has three phases:

    1. accelerate at constant proper acceleration `1g`
    2. coast at constant velocity
    3. decelerate at `1g` to arrive at rest

    The controls are measured in the traveler's proper time.
    """)
    return


@app.cell
def _(mo):
    tau_acc_years = mo.ui.slider(0.0, 20.0, step=0.1, value=1.0, label="Ship acceleration time τ_acc (years)", show_value=True)
    tau_coast_years = mo.ui.slider(0.0, 30.0, step=0.1, value=0.0, label="Ship coasting time τ_coast (years)", show_value=True)
    return tau_acc_years, tau_coast_years


@app.cell
def _(
    draw_worldlines,
    exp,
    g0,
    g1,
    gm,
    mo,
    np,
    sandwich,
    sta,
    tau_acc_years,
    tau_coast_years,
):
    _c = sta.scalar(299_792_458.0).name("c")
    _g = sta.scalar(9.80665).name("g")
    _t_s = sta.scalar(365.25 * 24 * 60 * 60).name(latex=r"t_s")
    _light_year_m = _c * _t_s

    _tau_acc = sta.scalar(tau_acc_years.value).name(latex=r"\tau_{acc}") * _t_s
    _tau_coast = tau_coast_years.value * _t_s

    _phi = (_g * _tau_acc / _c).name(latex=r"\phi")
    _beta = np.tanh(_phi.scalar_part)
    _gamma = np.cosh(_phi.scalar_part)

    _t_acc = (_c / _g) * np.sinh(_phi.scalar_part)
    _x_acc = (_c**2 / _g) * (np.cosh(_phi.scalar_part) - 1.0)

    _t_coast = _gamma * _tau_coast
    _x_coast = _beta * _c * _t_coast

    _total_ship_time_s = 2.0 * _tau_acc + _tau_coast
    _total_earth_time_s = 2.0 * _t_acc + _t_coast
    _total_ship_time_y = (_total_ship_time_s / _t_s).name(latex="years_{ship}")
    _total_earth_time_y = (_total_earth_time_s / _t_s).name(latex="years_{earth}")
    _total_distance = 2.0 * _x_acc + _x_coast

    _B = (g0 * g1).name("B")
    _phi_mv = (_phi + 0 * g0).name(latex=r"\varphi")
    _Lambda = exp((_phi / 2) * _B).name(latex=r"\Lambda")
    _ship_time_axis = sandwich(_Lambda, g0).name(latex=r"\gamma_0'")

    _md = t"""
    {_B.display()} <br/>
    {_phi.display()} <br/>
    {_phi_mv.display()} <br/>
    {_Lambda.display()} <br/>
    {_ship_time_axis.display()} <br/>
    Peak speed: {_beta:.14f}c $\\quad and \\quad \\gamma$ = {_gamma:,.4f} <br/>
    {(_total_ship_time_y).display():.3f} years <br/>
    {(_total_earth_time_y).display():,.3f} years <br/>
    Earth-frame distance: {_total_distance / _light_year_m:,.3f} light-years <br/>
    Each acceleration leg covers {_x_acc / _light_year_m:,.3f} light-years; the coast covers {_x_coast / _light_year_m:,.3f} light-years.
    """

    mo.vstack([
        tau_acc_years,
        tau_coast_years,
        gm.md(_md),
        draw_worldlines(_beta, _c.scalar_part, _g.scalar_part, _light_year_m.scalar_part, _t_acc.scalar_part, _t_coast.scalar_part, _tau_acc.scalar_part, _tau_coast.scalar_part, _total_distance.scalar_part, _total_earth_time_s, _x_acc.scalar_part, _t_s.scalar_part),
    ])
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Why Rapidity Helps

    Ordinary velocity is bounded by the speed of light, but rapidity adds linearly. That is why constant proper acceleration looks so simple in relativistic kinematics: equal increments of ship time give equal increments of rapidity, while the Earth-frame worldline becomes a hyperbola.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Conclusion

    The `1g` travel problem is a good example of how spacetime algebra and rapidity simplify relativistic motion. The traveler experiences a simple proper-acceleration law, while Earth sees hyperbolic acceleration, time dilation, and large distances accumulating naturally from the same boost geometry.
    """)
    return


@app.cell
def _():
    return


if __name__ == "__main__":
    app.run()
