import marimo

__generated_with = "0.22.4"
app = marimo.App(width="medium")


@app.cell
def _():
    from galaga import Algebra, sandwich
    from galaga.blade_convention import b_cga
    import galaga_marimo as gm
    import marimo as mo
    import matplotlib.pyplot as plt
    import numpy as np

    return Algebra, b_cga, gm, mo, np, plt, sandwich


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # 2D CGA Translations on the Paraboloid

    A Euclidean translation moves a point in the plane. Upstairs, the lifted
    point moves along the paraboloid. In CGA, that motion is not added by hand:
    it is generated by a translator versor.
    """)
    return


@app.cell
def _(Algebra, b_cga):
    alg = Algebra(3, 1, blades=b_cga(euclidean=2, null_basis="plus_minus"))
    e1, e2, ep, em = alg.basis_vectors(lazy=True)
    return alg, e1, e2, em, ep


@app.cell
def _(mo):
    px = mo.ui.slider(-1.8, 1.8, step=0.05, value=-0.5, label="x along e1", show_value=True)
    py = mo.ui.slider(-1.8, 1.8, step=0.05, value=0.4, label="x along e2", show_value=True)
    tx = mo.ui.slider(-1.2, 1.2, step=0.05, value=0.9, label="t along e1", show_value=True)
    ty = mo.ui.slider(-1.2, 1.2, step=0.05, value=-0.3, label="t along e2", show_value=True)
    view_yaw = mo.ui.slider(-30, 30, step=1, value=0, label="View yaw", show_value=True)
    return px, py, tx, ty, view_yaw


@app.cell
def _(
    alg,
    e1,
    e2,
    em,
    ep,
    gm,
    mo,
    paraboloid_translation_plot,
    px,
    py,
    sandwich,
    tx,
    ty,
    view_yaw,
):
    half = alg.frac(1, 2)
    eo = (half * (em - ep)).name(latex=r"e_o")
    einf = (ep + em).name(latex=r"e_\infty")

    x = (px.value * e1 + py.value * e2).name(latex="x")
    t = (tx.value * e1 + ty.value * e2).name(latex="t")
    x_prime = (x + t).name(latex=r"x'")
    X = (eo + x + half * (x | x) * einf).name(latex="X")
    T = (alg.scalar(1) - half * t * einf).name(latex="T")
    X_prime = sandwich(T, X).name(latex=r"X' = T X \widetilde{T}")
    X_prime_check = (eo + x_prime + half * (x_prime | x_prime) * einf).name(latex=r"\operatorname{up}(x+t)")
    delta_check = (X_prime - X_prime_check).name(latex=r"X' - \operatorname{up}(x+t)")

    _md = t"""
    {x.display()} <br/>
    {t.display()} <br/>
    {x_prime.display()} <br/>
    {X.display()} <br/>
    {T.display()} <br/>
    {X_prime.display()} <br/>
    {X_prime_check.display()} <br/>
    {delta_check.display()} <br/>
    The paraboloid motion is generated by the translator $T$, not by relifting a second point by hand.
    """

    mo.vstack([px, py, tx, ty, view_yaw, gm.md(_md), paraboloid_translation_plot(x, x_prime, view_yaw.value)])
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Appendum: Plotting Code
    """)
    return


@app.cell(hide_code=True)
def _(np, plt):
    def paraboloid_translation_plot(x, x_prime, view_yaw_deg):
        _x = np.array(x.vector_part[:2], dtype=float)
        _xp = np.array(x_prime.vector_part[:2], dtype=float)
        _hx = 0.5 * float(np.dot(_x, _x))
        _hxp = 0.5 * float(np.dot(_xp, _xp))

        _grid = np.linspace(-1.8, 1.8, 80)
        _gx, _gy = np.meshgrid(_grid, _grid)
        _gz = 0.5 * (_gx**2 + _gy**2)

        _fig = plt.figure(figsize=(11.4, 5.2))
        _ax0 = _fig.add_subplot(121)
        _ax1 = _fig.add_subplot(122, projection="3d")

        _ax0.scatter([_x[0], _xp[0]], [_x[1], _xp[1]], color=["#2563eb", "#d62828"], s=55)
        _ax0.annotate("", xy=_xp, xytext=_x, arrowprops=dict(arrowstyle="-|>", color="#555555", lw=1.8, alpha=0.8))
        _ax0.set_xlim(-1.9, 1.9)
        _ax0.set_ylim(-1.9, 1.9)
        _ax0.set_aspect("equal")
        _ax0.grid(True, alpha=0.18)
        _ax0.set_xlabel(r"$\mathbf{e_1}$")
        _ax0.set_ylabel(r"$\mathbf{e_2}$")
        _ax0.set_title("Euclidean translation")

        _ax1.plot_surface(_gx, _gy, _gz, color="#ddd6fe", alpha=0.28, linewidth=0, shade=False)
        for _xy, _h, _color in [(_x, _hx, "#2563eb"), (_xp, _hxp, "#d62828")]:
            _ax1.scatter([_xy[0]], [_xy[1]], [0], color=_color, s=28, alpha=0.55)
            _ax1.scatter([_xy[0]], [_xy[1]], [_h], color=_color, s=52)
            _ax1.plot([_xy[0], _xy[0]], [_xy[1], _xy[1]], [0, _h], color=_color, alpha=0.28, linewidth=1.6)
        _ax1.plot([_x[0], _xp[0]], [_x[1], _xp[1]], [_hx, _hxp], color="#444444", alpha=0.5, linewidth=1.4)
        _ax1.set_xlim(-1.9, 1.9)
        _ax1.set_ylim(-1.9, 1.9)
        _ax1.set_zlim(0, 3.4)
        _ax1.set_box_aspect((1, 1, 0.85))
        _ax1.view_init(elev=22, azim=-58 + view_yaw_deg)
        _ax1.set_xlabel(r"$\mathbf{e_1}$")
        _ax1.set_ylabel(r"$\mathbf{e_2}$")
        _ax1.set_zlabel(r"$e_\infty\ \mathrm{coeff}$")
        _ax1.set_title("Translated lift upstairs")

        plt.close(_fig)
        return _fig

    return (paraboloid_translation_plot,)


@app.cell
def _():
    return


if __name__ == "__main__":
    app.run()
