import marimo

__generated_with = "0.22.4"
app = marimo.App(width="medium")


@app.cell
def _():
    from galaga import Algebra
    from galaga.blade_convention import b_default
    import galaga_marimo as gm
    import marimo as mo
    import numpy as np
    import matplotlib.pyplot as plt

    return Algebra, b_default, gm, mo, np, plt


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Inertia Tensor as a Bivector-to-Bivector Map

    The inertia tensor is usually taught as a matrix acting on an angular-velocity
    vector. Geometrically, the cleaner statement is that it maps one rotational
    plane element to another: angular-velocity bivectors to angular-momentum
    bivectors.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    We use $\mathrm{Cl}(3,0)$ and model the body as three point masses.

    For a rotation generated by the bivector

    $$
    \Omega = \omega \widehat B,
    $$

    each mass point has velocity

    $$
    v_i = \Omega \cdot r_i,
    $$

    and contributes

    $$
    L_i = r_i \wedge (m_i v_i)
    $$

    to the total angular-momentum bivector.
    """)
    return


@app.cell
def _(Algebra, b_default):
    alg = Algebra((1, 1, 1), blades=b_default())
    e1, e2, e3 = alg.basis_vectors(lazy=True)
    return alg, e1, e2, e3


@app.cell
def _(mo):
    plane = mo.ui.dropdown(options=["e12 plane", "e23 plane", "e13 plane"], value="e12 plane", label="Angular-velocity plane")
    omega = mo.ui.slider(-2.0, 2.0, step=0.05, value=1.0, label="Angular speed ω", show_value=True)
    x2 = mo.ui.slider(-2.0, 2.0, step=0.05, value=1.1, label="Mass 2 x", show_value=True)
    y2 = mo.ui.slider(-2.0, 2.0, step=0.05, value=0.2, label="Mass 2 y", show_value=True)
    z2 = mo.ui.slider(-2.0, 2.0, step=0.05, value=0.4, label="Mass 2 z", show_value=True)
    x3 = mo.ui.slider(-2.0, 2.0, step=0.05, value=-0.4, label="Mass 3 x", show_value=True)
    y3 = mo.ui.slider(-2.0, 2.0, step=0.05, value=1.0, label="Mass 3 y", show_value=True)
    z3 = mo.ui.slider(-2.0, 2.0, step=0.05, value=0.7, label="Mass 3 z", show_value=True)
    return omega, plane, x2, x3, y2, y3, z2, z3


@app.cell
def _(
    alg,
    draw_inertia_bivector_map,
    e1,
    e2,
    e3,
    gm,
    mo,
    omega,
    plane,
    x2,
    x3,
    y2,
    y3,
    z2,
    z3,
):
    _plane_data = {
        "e12 plane": {"blade": (e1 * e2).name(latex=r"\hat B"), "basis_blades": (e1 * e2, e2 * e3, e3 * e1)},
        "e23 plane": {"blade": (e2 * e3).name(latex=r"\hat B"), "basis_blades": (e1 * e2, e2 * e3, e3 * e1)},
        "e13 plane": {"blade": (e1 * e3).name(latex=r"\hat B"), "basis_blades": (e1 * e2, e2 * e3, e3 * e1)},
    }[plane.value]

    B_hat = _plane_data["blade"]
    w = alg.scalar(omega.value).name(latex=r"\omega")
    Omega = (w * B_hat).name(latex=r"\Omega")

    m1 = alg.scalar(1.0).name(latex=r"m_1")
    m2 = alg.scalar(1.0).name(latex=r"m_2")
    m3 = alg.scalar(1.0).name(latex=r"m_3")

    r1 = (0.8 * e1 + 0.0 * e2 + 0.2 * e3).name(latex=r"r_1")
    r2 = (x2.value * e1 + y2.value * e2 + z2.value * e3).name(latex=r"r_2")
    r3 = (x3.value * e1 + y3.value * e2 + z3.value * e3).name(latex=r"r_3")

    def _vel(_r, _m, _label_v, _label_L):
        _v = (Omega | _r).name(latex=_label_v)
        _L = (_r ^ (_m * _v)).name(latex=_label_L)
        return _v, _L

    v1, L1 = _vel(r1, m1, r"v_1", r"L_1")
    v2, L2 = _vel(r2, m2, r"v_2", r"L_2")
    v3, L3 = _vel(r3, m3, r"v_3", r"L_3")
    L = (L1 + L2 + L3).name(latex="L")

    e12 = (e1 * e2).name(latex=r"e_{12}")
    e23 = (e2 * e3).name(latex=r"e_{23}")
    e31 = (e3 * e1).name(latex=r"e_{31}")
    L12 = (L | e12)
    L23 = (L | e23)
    L31 = (L | e31)

    _md = rt"""
    {B_hat.display()} <br/>
    {w.display()} <br/>
    {Omega.display()} <br/>
    {r1.display()} <br/>
    {r2.display()} <br/>
    {r3.display()} <br/>
    {v1.display()} <br/>
    {v2.display()} <br/>
    {v3.display()} <br/>
    {L1.display()} <br/>
    {L2.display()} <br/>
    {L3.display()} <br/>
    {L.display()} <br/>
    {L12.display()} <br/>
    {L23.display()} <br/>
    {L31.display()} <br/>
    The body shape determines how the input rotation plane $\Omega$ is mapped into the output angular-momentum bivector $L$.
    """

    mo.vstack(
        [
            plane,
            omega,
            x2,
            y2,
            z2,
            x3,
            y3,
            z3,
            gm.md(_md),
            draw_inertia_bivector_map(r1, r2, r3, v1, v2, v3, Omega, L),
        ]
    )
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Key Point

    The rigid body does not turn an angular-velocity “axis vector” into an
    angular-momentum “axis vector.” It maps one plane quantity to another. In
    symmetric bodies those planes can align; in generic bodies they do not have to.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Appendum: Plotting Code
    """)
    return


@app.cell(hide_code=True)
def _(e1, e2, e3, np, plt):
    def _vec(_mv):
        return np.array(_mv.eval().vector_part[:3], dtype=float)

    def _bivec_coeffs(_mv):
        _e12 = e1 * e2
        _e23 = e2 * e3
        _e31 = e3 * e1
        return np.array(
            [
                (_mv.eval() | _e12.eval()).scalar_part / ((_e12.eval() | _e12.eval()).scalar_part),
                (_mv.eval() | _e23.eval()).scalar_part / ((_e23.eval() | _e23.eval()).scalar_part),
                (_mv.eval() | _e31.eval()).scalar_part / ((_e31.eval() | _e31.eval()).scalar_part),
            ],
            dtype=float,
        )

    def draw_inertia_bivector_map(r1, r2, r3, v1, v2, v3, Omega, L):
        _r1, _r2, _r3 = _vec(r1), _vec(r2), _vec(r3)
        _v1, _v2, _v3 = _vec(v1), _vec(v2), _vec(v3)
        _Omega = _bivec_coeffs(Omega)
        _L = _bivec_coeffs(L)

        _fig = plt.figure(figsize=(12.4, 5.3))
        _ax0 = _fig.add_subplot(121, projection="3d")
        _ax1 = _fig.add_subplot(122)

        for _r, _v, _color, _label in [(_r1, _v1, "#222222", "1"), (_r2, _v2, "#2563eb", "2"), (_r3, _v3, "#d62828", "3")]:
            _ax0.scatter([_r[0]], [_r[1]], [_r[2]], color=_color, s=50)
            _ax0.text(_r[0] + 0.05, _r[1] + 0.05, _r[2] + 0.05, _label, color=_color)
            _ax0.quiver(_r[0], _r[1], _r[2], _v[0], _v[1], _v[2], color=_color, linewidth=2.0, arrow_length_ratio=0.18)
        _ax0.set_xlim(-2.2, 2.2)
        _ax0.set_ylim(-2.2, 2.2)
        _ax0.set_zlim(-2.2, 2.2)
        _ax0.set_box_aspect((1, 1, 1))
        _ax0.set_xlabel("e1")
        _ax0.set_ylabel("e2")
        _ax0.set_zlabel("e3")
        _ax0.set_title("Point masses and their velocities")

        _x = np.arange(3)
        _w = 0.34
        _ax1.bar(_x - _w / 2, _Omega, width=_w, color="#7c3aed", alpha=0.84, label=r"$\Omega$")
        _ax1.bar(_x + _w / 2, _L, width=_w, color="#10b981", alpha=0.84, label=r"$L$")
        _ax1.axhline(0, color="#333333", lw=1.0, alpha=0.45)
        _ax1.set_xticks(_x, [r"$e_{12}$", r"$e_{23}$", r"$e_{31}$"])
        _ax1.grid(True, axis="y", alpha=0.18)
        _ax1.set_title("Bivector input/output channels")
        _ax1.legend(loc="upper right")

        plt.close(_fig)
        return _fig

    return (draw_inertia_bivector_map,)


@app.cell
def _():
    return


if __name__ == "__main__":
    app.run()
