import marimo

__generated_with = "0.22.4"
app = marimo.App(width="medium")


@app.cell
def _():
    from galaga import Algebra, exp
    from galaga.blade_convention import b_default
    import galaga_marimo as gm
    import marimo as mo
    import numpy as np
    import matplotlib.pyplot as plt

    return Algebra, b_default, exp, gm, mo, np, plt


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Rotating Frames in GA

    Coriolis and centrifugal terms are not extra forces pasted onto Newton's law.
    They appear because the observer's frame is itself rotating.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    We use $\mathrm{Cl}(3,0)$ and keep the motion in the $e_1$-$e_2$ plane.

    A rotating observer frame is described by a rotor

    $$
    R(t) = e^{-\frac{1}{2}\Omega t},
    \qquad
    \Omega = \omega e_{12}.
    $$

    If the inertial motion is straight-line and force-free, the rotating observer
    still sees extra terms because the frame itself is changing.
    """)
    return


@app.cell
def _(Algebra, b_default):
    alg = Algebra((1, 1, 1), blades=b_default())
    e1, e2, e3 = alg.basis_vectors(lazy=True)
    return alg, e1, e2, e3


@app.cell
def _(mo):
    omega = mo.ui.slider(-3.0, 3.0, step=0.05, value=1.0, label="Frame angular speed ω", show_value=True)
    x0 = mo.ui.slider(-2.0, 2.0, step=0.05, value=1.0, label="Initial x", show_value=True)
    y0 = mo.ui.slider(-2.0, 2.0, step=0.05, value=0.3, label="Initial y", show_value=True)
    vx = mo.ui.slider(-2.0, 2.0, step=0.05, value=0.7, label="Inertial v_x", show_value=True)
    vy = mo.ui.slider(-2.0, 2.0, step=0.05, value=0.0, label="Inertial v_y", show_value=True)
    time = mo.ui.slider(0.0, 4.0, step=0.05, value=1.5, label="Time t", show_value=True)
    return omega, time, vx, vy, x0, y0


@app.cell
def _(alg, draw_rotating_frames, e1, e2, exp, gm, mo, np, omega, time, vx, vy, x0, y0):
    half = alg.frac(1, 2)
    t = alg.scalar(time.value).name(latex="t")
    w = alg.scalar(omega.value).name(latex=r"\omega")
    Omega = (w * (e1 * e2)).name(latex=r"\Omega")
    R = exp(-(Omega * t) * half).name(latex="R")

    x_in = ((x0.value + vx.value * time.value) * e1 + (y0.value + vy.value * time.value) * e2).name(latex=r"x_I")
    v_in = (vx.value * e1 + vy.value * e2).name(latex=r"v_I")
    a_in = (alg.scalar(0) * e1).name(latex=r"a_I")

    x_rot = (R * x_in * ~R).name(latex=r"x_R")
    v_rot_direct = (R * v_in * ~R).name(latex=r"v_R")

    _x = np.array(x_rot.eval().vector_part[:3], dtype=float)
    _v = np.array(v_rot_direct.eval().vector_part[:3], dtype=float)
    _omega_vec = np.array([0.0, 0.0, omega.value], dtype=float)
    _coriolis = -2.0 * np.cross(_omega_vec, _v)
    _centrifugal = -np.cross(_omega_vec, np.cross(_omega_vec, _x))
    _apparent = _coriolis + _centrifugal

    coriolis = (_coriolis[0] * e1 + _coriolis[1] * e2).name(latex=r"a_{\mathrm{Cor}}")
    centrifugal = (_centrifugal[0] * e1 + _centrifugal[1] * e2).name(latex=r"a_{\mathrm{cen}}")
    apparent = (_apparent[0] * e1 + _apparent[1] * e2).name(latex=r"a_{\mathrm{app}}")

    _md = t"""
    {w.display()} <br/>
    {t.display()} <br/>
    {Omega.display()} <br/>
    {R.display()} <br/>
    {x_in.display()} <br/>
    {v_in.display()} <br/>
    {a_in.display()} <br/>
    {x_rot.display()} <br/>
    {v_rot_direct.display()} <br/>
    {coriolis.display()} <br/>
    {centrifugal.display()} <br/>
    {apparent.display()} <br/>
    The inertial motion is force-free, but the rotating observer sees Coriolis and centrifugal terms because the frame rotor is time-dependent.
    """

    mo.vstack([omega, x0, y0, vx, vy, time, gm.md(_md), draw_rotating_frames(omega.value, x0.value, y0.value, vx.value, vy.value, time.value)])
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Key Point

    The fictitious forces are not mysterious. They are bookkeeping terms caused by
    differentiating with a moving rotor frame. GA makes that natural because the
    frame motion is already one geometric object: the rotor generated by the
    angular-velocity bivector.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""## Appendum: Plotting Code""")
    return


@app.cell(hide_code=True)
def _(np, plt):
    def _rot2(theta):
        return np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]], dtype=float)

    def draw_rotating_frames(omega, x0, y0, vx, vy, time):
        _ts = np.linspace(0.0, max(time, 1e-3), 220)
        _xin = np.stack([x0 + vx * _ts, y0 + vy * _ts], axis=1)
        _xrot = np.array([_rot2(-omega * _t) @ _x for _t, _x in zip(_ts, _xin)])

        _x_now = _xin[-1]
        _x_rot_now = _xrot[-1]
        _v_rot_now = _rot2(-omega * time) @ np.array([vx, vy], dtype=float)

        _omega_vec = np.array([0.0, 0.0, omega], dtype=float)
        _x3 = np.array([_x_rot_now[0], _x_rot_now[1], 0.0], dtype=float)
        _v3 = np.array([_v_rot_now[0], _v_rot_now[1], 0.0], dtype=float)
        _cor = -2.0 * np.cross(_omega_vec, _v3)[:2]
        _cen = -np.cross(_omega_vec, np.cross(_omega_vec, _x3))[:2]
        _app = _cor + _cen

        _fig, (_ax0, _ax1) = plt.subplots(1, 2, figsize=(11.8, 5.0))

        _ax0.plot(_xin[:, 0], _xin[:, 1], color="#2563eb", linewidth=2.5, label="inertial path")
        _ax0.plot(_xrot[:, 0], _xrot[:, 1], color="#d62828", linewidth=2.5, label="rotating-frame path")
        _ax0.scatter([_x_now[0]], [_x_now[1]], color="#2563eb", s=36)
        _ax0.scatter([_x_rot_now[0]], [_x_rot_now[1]], color="#d62828", s=36)
        _ax0.set_aspect("equal")
        _ax0.set_xlim(-4.0, 4.0)
        _ax0.set_ylim(-4.0, 4.0)
        _ax0.grid(True, alpha=0.18)
        _ax0.set_xlabel("e1")
        _ax0.set_ylabel("e2")
        _ax0.set_title("Same motion in inertial and rotating coordinates")
        _ax0.legend(loc="upper right")

        _ax1.annotate("", xy=_cor, xytext=(0, 0), arrowprops=dict(arrowstyle="-|>", color="#2563eb", lw=2.5, mutation_scale=18))
        _ax1.annotate("", xy=_cen, xytext=(0, 0), arrowprops=dict(arrowstyle="-|>", color="#d62828", lw=2.5, mutation_scale=18))
        _ax1.annotate("", xy=_app, xytext=(0, 0), arrowprops=dict(arrowstyle="-|>", color="#7c3aed", lw=2.8, mutation_scale=18))
        _ax1.text(_cor[0] + 0.06, _cor[1] + 0.05, "Coriolis", color="#2563eb")
        _ax1.text(_cen[0] + 0.06, _cen[1] + 0.05, "centrifugal", color="#d62828")
        _ax1.text(_app[0] + 0.06, _app[1] + 0.05, "total", color="#7c3aed")
        _ax1.set_aspect("equal")
        _ax1.set_xlim(-4.0, 4.0)
        _ax1.set_ylim(-4.0, 4.0)
        _ax1.grid(True, alpha=0.18)
        _ax1.set_xlabel("e1")
        _ax1.set_ylabel("e2")
        _ax1.set_title("Apparent acceleration terms in the rotating frame")

        plt.close(_fig)
        return _fig

    return (draw_rotating_frames,)


@app.cell
def _():
    return


if __name__ == "__main__":
    app.run()
